--------------------------------------------------------
--  파일이 생성됨 - 월요일-12월-16-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table HOUSE
--------------------------------------------------------

  CREATE TABLE "PROJECT"."HOUSE" 
   (	"HOUSECODE" NUMBER(10,0), 
	"MEMBERCODE" NUMBER(10,0), 
	"HOUSENAME" VARCHAR2(100 BYTE), 
	"ZIPCODE" VARCHAR2(100 BYTE), 
	"EXPLAIN" VARCHAR2(1000 BYTE), 
	"BATH" NUMBER(5,0), 
	"ETC" VARCHAR2(500 BYTE), 
	"CHECKIN" VARCHAR2(20 BYTE), 
	"CHECKOUT" VARCHAR2(20 BYTE), 
	"NECESSARY" VARCHAR2(10 BYTE), 
	"WIFI" VARCHAR2(10 BYTE), 
	"WASHER" VARCHAR2(10 BYTE), 
	"HOTWATER" VARCHAR2(10 BYTE), 
	"AIRCON" VARCHAR2(10 BYTE), 
	"TV" VARCHAR2(10 BYTE), 
	"MART" VARCHAR2(10 BYTE), 
	"PARKING" VARCHAR2(10 BYTE), 
	"KITCHEN" VARCHAR2(10 BYTE), 
	"SAFETY" VARCHAR2(10 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"SIDO" VARCHAR2(300 BYTE), 
	"SIGUNGU" VARCHAR2(300 BYTE), 
	"ROADNAME" VARCHAR2(300 BYTE), 
	"BNAME" VARCHAR2(300 BYTE), 
	"JIBUNADDRESS" VARCHAR2(300 BYTE), 
	"LATLNG" VARCHAR2(300 BYTE), 
	"DETAILADDRESS" VARCHAR2(300 BYTE), 
	"LOCAL" VARCHAR2(300 BYTE), 
	"APPROVALSTATUS" VARCHAR2(300 BYTE), 
	"BANK" VARCHAR2(300 BYTE), 
	"ACCOUNT" NUMBER(13,0), 
	"PEOPLE" NUMBER(10,0), 
	"BED" NUMBER(10,0), 
	"PRICE" NUMBER(10,0), 
	"HOUSEREGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESERVATION
--------------------------------------------------------

  CREATE TABLE "PROJECT"."RESERVATION" 
   (	"RESERVECODE" NUMBER(5,0), 
	"PEOPLE" NUMBER(5,0), 
	"RESERVEDATE" DATE, 
	"CHECKIN" DATE, 
	"CHECKOUT" DATE, 
	"PAYMENT" NUMBER(10,0), 
	"MEMBERCODE" NUMBER(10,0), 
	"HOUSECODE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PROJECT.HOUSE
SET DEFINE OFF;
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (1,1,'기용이네 구좌','63359',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 제주시 구좌읍 계룡길 5','제주특별자치도','제주시','계룡길','한동리','제주특별자치도 제주시 구좌읍 한동리 19','(33.53630753279682, 126.83552349439641)','상세주소','jejuEast',null,null,null,4,4,18000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (2,1,'기용이네 애월','695-918',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 제주시 애월읍 가문동길 2','제주특별자치도','제주시','가문동길','하귀2리','제주특별자치도 제주시 애월읍 하귀2리 2615-9','(33.48378483975008, 126.3953553887375)','상세주소','jeju',null,null,null,3,3,15000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (3,1,'기용이네 조천','63341',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 제주시 조천읍 거문오름길 5','제주특별자치도','제주시','거문오름길','선흘리','제주특별자치도 제주시 조천읍 선흘리 475-125','(33.45958069198267, 126.71260417637251)','상세주소','jejuEast',null,null,null,4,4,16000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (4,1,'기용이네 한림','695-924',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 제주시 한림읍 가린내길 8','제주특별자치도','제주시','가린내길','금악리','제주특별자치도 제주시 한림읍 금악리 1025','(33.361557604273266, 126.30772059594068)','상세주소','jejuWest',null,null,null,5,5,20000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (5,2,'윤수네 남원','699-943',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 서귀포시 남원읍 공천포로 9','제주특별자치도','서귀포시','공천포로','신례리','제주특별자치도 서귀포시 남원읍 신례리 80-13','(33.264015809034724, 126.63929904423631)','상세주소','seoguipoWest',null,null,null,3,3,9000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (6,2,'윤수네 색달','697-807',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 서귀포시 중문관광로 7','제주특별자치도','서귀포시','중문관광로','색달동','제주특별자치도 서귀포시 색달동 2315-1','(33.25725733663533, 126.41540890624866)','상세주소','seoguipo',null,null,null,3,3,20000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (7,2,'윤수네 성산','699-901',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 서귀포시 성산읍 고성동서로51번길 2','제주특별자치도','서귀포시','고성동서로51번길','고성리','제주특별자치도 서귀포시 성산읍 고성리 1180-6','(33.45070122691018, 126.9129402214395)','상세주소','jejuWest',null,null,null,4,4,23000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (8,2,'윤수네 대정','699-935',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 서귀포시 대정읍 동일하모로220번길 19','제주특별자치도','서귀포시','동일하모로220번길','하모리','제주특별자치도 서귀포시 대정읍 하모리 1549-1','(33.22400912970608, 126.25480866715698)','상세주소','jejuWest',null,null,null,2,2,7000,null);
Insert into PROJECT.HOUSE (HOUSECODE,MEMBERCODE,HOUSENAME,ZIPCODE,EXPLAIN,BATH,ETC,CHECKIN,CHECKOUT,NECESSARY,WIFI,WASHER,HOTWATER,AIRCON,TV,MART,PARKING,KITCHEN,SAFETY,ADDRESS,SIDO,SIGUNGU,ROADNAME,BNAME,JIBUNADDRESS,LATLNG,DETAILADDRESS,LOCAL,APPROVALSTATUS,BANK,ACCOUNT,PEOPLE,BED,PRICE,HOUSEREGDATE) values (9,3,'태현이네 구좌','695-982',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'제주특별자치도 제주시 구좌읍 계룡길 11','제주특별자치도','제주시','계룡길','한동리','제주특별자치도 제주시 구좌읍 한동리 10-79','(33.53679079934821, 126.83553119212714)','상세주소','jejuWest',null,null,null,1,1,5000,null);
REM INSERTING into PROJECT.RESERVATION
SET DEFINE OFF;
Insert into PROJECT.RESERVATION (RESERVECODE,PEOPLE,RESERVEDATE,CHECKIN,CHECKOUT,PAYMENT,MEMBERCODE,HOUSECODE) values (1,2,to_date('19/12/14','RR/MM/DD'),to_date('19/12/18','RR/MM/DD'),to_date('19/12/20','RR/MM/DD'),72000,2,1);
Insert into PROJECT.RESERVATION (RESERVECODE,PEOPLE,RESERVEDATE,CHECKIN,CHECKOUT,PAYMENT,MEMBERCODE,HOUSECODE) values (2,2,to_date('19/12/14','RR/MM/DD'),to_date('19/12/20','RR/MM/DD'),to_date('19/12/22','RR/MM/DD'),60000,2,2);
Insert into PROJECT.RESERVATION (RESERVECODE,PEOPLE,RESERVEDATE,CHECKIN,CHECKOUT,PAYMENT,MEMBERCODE,HOUSECODE) values (3,2,to_date('19/12/14','RR/MM/DD'),to_date('19/12/18','RR/MM/DD'),to_date('19/12/20','RR/MM/DD'),80000,2,4);
Insert into PROJECT.RESERVATION (RESERVECODE,PEOPLE,RESERVEDATE,CHECKIN,CHECKOUT,PAYMENT,MEMBERCODE,HOUSECODE) values (4,1,to_date('19/12/14','RR/MM/DD'),to_date('19/12/20','RR/MM/DD'),to_date('19/12/21','RR/MM/DD'),7000,1,8);
Insert into PROJECT.RESERVATION (RESERVECODE,PEOPLE,RESERVEDATE,CHECKIN,CHECKOUT,PAYMENT,MEMBERCODE,HOUSECODE) values (5,1,to_date('19/12/15','RR/MM/DD'),to_date('19/12/15','RR/MM/DD'),to_date('19/12/16','RR/MM/DD'),18000,1,1);
--------------------------------------------------------
--  DDL for Index PK_HOUSE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."PK_HOUSE" ON "PROJECT"."HOUSE" ("HOUSECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RESERVATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PROJECT"."PK_RESERVATION" ON "PROJECT"."RESERVATION" ("RESERVECODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table HOUSE
--------------------------------------------------------

  ALTER TABLE "PROJECT"."HOUSE" ADD CONSTRAINT "PK_HOUSE" PRIMARY KEY ("HOUSECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."HOUSE" MODIFY ("MEMBERCODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."HOUSE" MODIFY ("HOUSECODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVATION
--------------------------------------------------------

  ALTER TABLE "PROJECT"."RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY ("RESERVECODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PROJECT"."RESERVATION" MODIFY ("HOUSECODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."RESERVATION" MODIFY ("MEMBERCODE" NOT NULL ENABLE);
  ALTER TABLE "PROJECT"."RESERVATION" MODIFY ("RESERVECODE" NOT NULL ENABLE);
