spring:
  mvc:
    view:
      prefix: WEB-INF
      suffix: .jsp
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
login:
  kakao:
    key:
      rest-api: please-set-restapikey-on-the-application-key-yml-file
