spring:
  mvc:
    view:
      prefix: WEB-INF
      suffix: .jsp
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
