DROP TABLE IF EXISTS day_of_room CASCADE;
DROP TABLE IF EXISTS guest_house CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS room CASCADE;

create table day_of_room (
                             id bigint generated by default as identity,
                             date date,
                             remain_count integer,
                             room_id bigint,
                             primary key (id)
);

create table guest_house (
                             id bigint generated by default as identity,
                             name varchar(255),
                             host_id bigint,
                             primary key (id)
);

create table member (
                        id bigint generated by default as identity,
                        created_date timestamp,
                        email varchar(255),
                        member_img_name varchar(255),
                        member_img_path varchar(255),
                        member_img_size bigint not null,
                        member_info varchar(255),
                        member_level varchar(255),
                        name varchar(255),
                        password varchar(255),
                        phone_number varchar(255),
                        point integer not null,
                        primary key (id)
);

create table room (
                      id bigint generated by default as identity,
                      guests_count integer,
                      name varchar(255),
                      guest_house_id bigint,
                      primary key (id)
);
